[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"
evm_version = "prague"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@vault-periphery/=lib/vault-periphery/contracts/",
    "@yearn-vaults-v3/=lib/yearn-vaults-v3/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config