[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'shanghai'
solc = "0.8.22"


remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config